//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated automatically by SystemGroup Redesigner tool V2.7.0.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemGroup.General.CourseEnrollment.Web.SemesterCoursePlanPages
{


    public partial class EditClass 
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// scriptManager control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SystemGroup.Web.UI.Controls.SgScriptManager scriptManager;

        /// <summary>
        /// updMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SystemGroup.Web.UI.Controls.SgUpdatePanel updMain;

        /// <summary>
        /// dvMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dvMain;

        /// <summary>
        /// grdParties control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SystemGroup.Web.UI.Controls.SgGrid grdParties;
    }
}
