//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated automatically by SystemGroup Redesigner tool V2.7.0.0.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemGroup.General.CourseEnrollment.Web.CoursePages
{


    public partial class Edit 
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// scriptManager control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SystemGroup.Web.UI.Controls.SgScriptManager scriptManager;

        /// <summary>
        /// updMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SystemGroup.Web.UI.Controls.SgUpdatePanel updMain;

        /// <summary>
        /// dvMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dvMain;

        /// <summary>
        /// fldsetMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SystemGroup.Web.UI.Controls.SgFieldSet fldsetMain;

        /// <summary>
        /// txtName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SystemGroup.Web.UI.Controls.SgTextBox txtName;

        /// <summary>
        /// txtUnits control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SystemGroup.Web.UI.Controls.SgNumericTextBox txtUnits;

        /// <summary>
        /// tbsTab control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SystemGroup.Web.UI.Controls.SgTabStrip tbsTab;

        /// <summary>
        /// mpgMultiPage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SystemGroup.Web.UI.Controls.SgMultiPage mpgMultiPage;

        /// <summary>
        /// rpvGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.RadPageView rpvGrid;

        /// <summary>
        /// grdPrerequisites control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SystemGroup.Web.UI.Controls.SgGrid grdPrerequisites;
    }
}
